#define { outercurve-publickeytoken: "1e373a58e25250cb"; }

#define { deps-publickeytoken: "${outercurve-publickeytoken}"; }

#define { pixman-dep-version: "0.24.0"; }

#define { pixman-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { libpng-dep-version: "1.5.4"; }

#define { libpng-dep-publickeytoken: "${deps-publickeytoken}"; }

#define { glib-dep-version: "2.32.3"; }

#define { glib-dep-publickeytoken: "${deps-publickeytoken}"; }
